run:
  # Our CI expects a vendor directory, hence we have to use -mod=readonly here as well.
  modules-download-mode: readonly
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m

issues:
  # on default, golangci-lint excludes gosec. Hence, we have to
  # explicitly disable the exclude-use-default: https://github.com/golangci/golangci-lint/issues/1504
  exclude-use-default: false

# default linters are enabled `golangci-lint help linters`
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gocritic
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
