apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: test-cad
  namespace: default
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: "test-cad"
  unhealthyPodEvictionPolicy: AlwaysAllow
