// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/backplane/backplane.go
//
// Generated by this command:
//
//	mockgen -source=pkg/backplane/backplane.go
//

// Package mock_backplane is a generated GoMock package.
package mock_backplane

import (
	context "context"
	reflect "reflect"

	Openapi "github.com/openshift/backplane-api/pkg/client"
	backplane "github.com/openshift/configuration-anomaly-detection/pkg/backplane"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateReport mocks base method.
func (m *MockClient) CreateReport(ctx context.Context, clusterId, summary, reportData string) (*Openapi.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReport", ctx, clusterId, summary, reportData)
	ret0, _ := ret[0].(*Openapi.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReport indicates an expected call of CreateReport.
func (mr *MockClientMockRecorder) CreateReport(ctx, clusterId, summary, reportData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReport", reflect.TypeOf((*MockClient)(nil).CreateReport), ctx, clusterId, summary, reportData)
}

// GetRestConfig mocks base method.
func (m *MockClient) GetRestConfig(ctx context.Context, clusterId, remediationName string, isManagementCluster bool) (*backplane.RestConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestConfig", ctx, clusterId, remediationName, isManagementCluster)
	ret0, _ := ret[0].(*backplane.RestConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestConfig indicates an expected call of GetRestConfig.
func (mr *MockClientMockRecorder) GetRestConfig(ctx, clusterId, remediationName, isManagementCluster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestConfig", reflect.TypeOf((*MockClient)(nil).GetRestConfig), ctx, clusterId, remediationName, isManagementCluster)
}

// GetRestConfigWithManagingClusterType mocks base method.
func (m *MockClient) GetRestConfigWithManagingClusterType(ctx context.Context, clusterId, remediationName string, managingClusterType backplane.ManagingClusterType) (*backplane.RestConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestConfigWithManagingClusterType", ctx, clusterId, remediationName, managingClusterType)
	ret0, _ := ret[0].(*backplane.RestConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestConfigWithManagingClusterType indicates an expected call of GetRestConfigWithManagingClusterType.
func (mr *MockClientMockRecorder) GetRestConfigWithManagingClusterType(ctx, clusterId, remediationName, managingClusterType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestConfigWithManagingClusterType", reflect.TypeOf((*MockClient)(nil).GetRestConfigWithManagingClusterType), ctx, clusterId, remediationName, managingClusterType)
}

// MockCleaner is a mock of Cleaner interface.
type MockCleaner struct {
	ctrl     *gomock.Controller
	recorder *MockCleanerMockRecorder
	isgomock struct{}
}

// MockCleanerMockRecorder is the mock recorder for MockCleaner.
type MockCleanerMockRecorder struct {
	mock *MockCleaner
}

// NewMockCleaner creates a new mock instance.
func NewMockCleaner(ctrl *gomock.Controller) *MockCleaner {
	mock := &MockCleaner{ctrl: ctrl}
	mock.recorder = &MockCleanerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCleaner) EXPECT() *MockCleanerMockRecorder {
	return m.recorder
}

// Clean mocks base method.
func (m *MockCleaner) Clean() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean")
	ret0, _ := ret[0].(error)
	return ret0
}

// Clean indicates an expected call of Clean.
func (mr *MockCleanerMockRecorder) Clean() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*MockCleaner)(nil).Clean))
}
