// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/rhobs/rhobs.go
//
// Generated by this command:
//
//	mockgen -source=pkg/rhobs/rhobs.go -destination=pkg/rhobs/mock/rhobsmock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	rhobs "github.com/openshift/configuration-anomaly-detection/pkg/rhobs"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// QueryLogs mocks base method.
func (m *MockClient) QueryLogs(ctx context.Context, logQLQuery string, start, end time.Time, limit int) (*rhobs.LogQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryLogs", ctx, logQLQuery, start, end, limit)
	ret0, _ := ret[0].(*rhobs.LogQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryLogs indicates an expected call of QueryLogs.
func (mr *MockClientMockRecorder) QueryLogs(ctx, logQLQuery, start, end, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryLogs", reflect.TypeOf((*MockClient)(nil).QueryLogs), ctx, logQLQuery, start, end, limit)
}
