apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cad-pvc
  namespace: configuration-anomaly-detection
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
