---
apiVersion: v1
kind: Secret
metadata:
  name: cad-ocm-client-secret
  namespace: configuration-anomaly-detection
type: Opaque
stringData:
  CAD_OCM_CLIENT_ID: ocm-cad-staging
  CAD_OCM_CLIENT_SECRET: CHANGEME
  CAD_OCM_URL: "https://api.stage.openshift.com"
