#!/usr/bin/env bash

set -e

source $CONVENTION_ROOT/_lib/common.sh

# No PRE
[[ "$1" == "PRE" ]] && exit 0

# Expect POST
[[ "$1" == "POST" ]] || err "Got a parameter I don't understand: '$1'. Did the infrastructure change?"

echo "Writing .ci-operator.yaml in your repository root with:"
echo "    namespace: $IMAGE_NAMESPACE"
echo "    name: $IMAGE_NAME"
echo "    tag: $LATEST_IMAGE_TAG"
${SED?} "s/__NAMESPACE__/$IMAGE_NAMESPACE/; s/__NAME__/$IMAGE_NAME/; s/__TAG__/$LATEST_IMAGE_TAG/" ${HERE}/.ci-operator.yaml > $REPO_ROOT/.ci-operator.yaml

cat <<EOF

=====================
THINGS YOU NEED TO DO
=====================
- Make sure the following line is in your base Makefile:

include boilerplate/generated-includes.mk

- Remove any other 'include' lines, unless they're for things truly
  unique to your repository. (Otherwise, consider proposing them to
  boilerplate.)

- Delete any obsolete files you're no longer including.

- Define a `make test` target for Prow

- Have a Dockerfile in ./build/Dockerfile and define IMAGE_NAME for it.
  Others container images can be specified with ADDITIONAL_IMAGE_SPECS

=====================

EOF
