// Code generated by MockGen. DO NOT EDIT.
// Source: aws.go
//
// Generated by this command:
//
//	mockgen -source=aws.go -package=awsmock -destination=mock/aws.go
//

// Package awsmock is a generated GoMock package.
package awsmock

import (
	context "context"
	reflect "reflect"

	aws "github.com/aws/aws-sdk-go-v2/aws"
	bedrockagentcore "github.com/aws/aws-sdk-go-v2/service/bedrockagentcore"
	cloudtrail "github.com/aws/aws-sdk-go-v2/service/cloudtrail"
	types "github.com/aws/aws-sdk-go-v2/service/cloudtrail/types"
	ec2 "github.com/aws/aws-sdk-go-v2/service/ec2"
	types0 "github.com/aws/aws-sdk-go-v2/service/ec2/types"
	elasticloadbalancing "github.com/aws/aws-sdk-go-v2/service/elasticloadbalancing"
	elasticloadbalancingv2 "github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2"
	route53 "github.com/aws/aws-sdk-go-v2/service/route53"
	sts "github.com/aws/aws-sdk-go-v2/service/sts"
	aws0 "github.com/openshift/configuration-anomaly-detection/pkg/aws"
	gomock "go.uber.org/mock/gomock"
)

// MockEC2API is a mock of EC2API interface.
type MockEC2API struct {
	ctrl     *gomock.Controller
	recorder *MockEC2APIMockRecorder
	isgomock struct{}
}

// MockEC2APIMockRecorder is the mock recorder for MockEC2API.
type MockEC2APIMockRecorder struct {
	mock *MockEC2API
}

// NewMockEC2API creates a new mock instance.
func NewMockEC2API(ctrl *gomock.Controller) *MockEC2API {
	mock := &MockEC2API{ctrl: ctrl}
	mock.recorder = &MockEC2APIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2API) EXPECT() *MockEC2APIMockRecorder {
	return m.recorder
}

// DescribeDhcpOptions mocks base method.
func (m *MockEC2API) DescribeDhcpOptions(ctx context.Context, in *ec2.DescribeDhcpOptionsInput, optFns ...func(*ec2.Options)) (*ec2.DescribeDhcpOptionsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeDhcpOptions", varargs...)
	ret0, _ := ret[0].(*ec2.DescribeDhcpOptionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDhcpOptions indicates an expected call of DescribeDhcpOptions.
func (mr *MockEC2APIMockRecorder) DescribeDhcpOptions(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDhcpOptions", reflect.TypeOf((*MockEC2API)(nil).DescribeDhcpOptions), varargs...)
}

// DescribeInstances mocks base method.
func (m *MockEC2API) DescribeInstances(ctx context.Context, in *ec2.DescribeInstancesInput, optFns ...func(*ec2.Options)) (*ec2.DescribeInstancesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeInstances", varargs...)
	ret0, _ := ret[0].(*ec2.DescribeInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeInstances indicates an expected call of DescribeInstances.
func (mr *MockEC2APIMockRecorder) DescribeInstances(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeInstances", reflect.TypeOf((*MockEC2API)(nil).DescribeInstances), varargs...)
}

// DescribeRouteTables mocks base method.
func (m *MockEC2API) DescribeRouteTables(ctx context.Context, in *ec2.DescribeRouteTablesInput, optFns ...func(*ec2.Options)) (*ec2.DescribeRouteTablesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeRouteTables", varargs...)
	ret0, _ := ret[0].(*ec2.DescribeRouteTablesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeRouteTables indicates an expected call of DescribeRouteTables.
func (mr *MockEC2APIMockRecorder) DescribeRouteTables(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeRouteTables", reflect.TypeOf((*MockEC2API)(nil).DescribeRouteTables), varargs...)
}

// DescribeSecurityGroups mocks base method.
func (m *MockEC2API) DescribeSecurityGroups(ctx context.Context, in *ec2.DescribeSecurityGroupsInput, optFns ...func(*ec2.Options)) (*ec2.DescribeSecurityGroupsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeSecurityGroups", varargs...)
	ret0, _ := ret[0].(*ec2.DescribeSecurityGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeSecurityGroups indicates an expected call of DescribeSecurityGroups.
func (mr *MockEC2APIMockRecorder) DescribeSecurityGroups(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeSecurityGroups", reflect.TypeOf((*MockEC2API)(nil).DescribeSecurityGroups), varargs...)
}

// DescribeSubnets mocks base method.
func (m *MockEC2API) DescribeSubnets(ctx context.Context, in *ec2.DescribeSubnetsInput, optFns ...func(*ec2.Options)) (*ec2.DescribeSubnetsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeSubnets", varargs...)
	ret0, _ := ret[0].(*ec2.DescribeSubnetsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeSubnets indicates an expected call of DescribeSubnets.
func (mr *MockEC2APIMockRecorder) DescribeSubnets(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeSubnets", reflect.TypeOf((*MockEC2API)(nil).DescribeSubnets), varargs...)
}

// DescribeVpcs mocks base method.
func (m *MockEC2API) DescribeVpcs(ctx context.Context, in *ec2.DescribeVpcsInput, optFns ...func(*ec2.Options)) (*ec2.DescribeVpcsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeVpcs", varargs...)
	ret0, _ := ret[0].(*ec2.DescribeVpcsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeVpcs indicates an expected call of DescribeVpcs.
func (mr *MockEC2APIMockRecorder) DescribeVpcs(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeVpcs", reflect.TypeOf((*MockEC2API)(nil).DescribeVpcs), varargs...)
}

// MockCloudTrailAPI is a mock of CloudTrailAPI interface.
type MockCloudTrailAPI struct {
	ctrl     *gomock.Controller
	recorder *MockCloudTrailAPIMockRecorder
	isgomock struct{}
}

// MockCloudTrailAPIMockRecorder is the mock recorder for MockCloudTrailAPI.
type MockCloudTrailAPIMockRecorder struct {
	mock *MockCloudTrailAPI
}

// NewMockCloudTrailAPI creates a new mock instance.
func NewMockCloudTrailAPI(ctrl *gomock.Controller) *MockCloudTrailAPI {
	mock := &MockCloudTrailAPI{ctrl: ctrl}
	mock.recorder = &MockCloudTrailAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudTrailAPI) EXPECT() *MockCloudTrailAPIMockRecorder {
	return m.recorder
}

// LookupEvents mocks base method.
func (m *MockCloudTrailAPI) LookupEvents(ctx context.Context, in *cloudtrail.LookupEventsInput, optFns ...func(*cloudtrail.Options)) (*cloudtrail.LookupEventsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LookupEvents", varargs...)
	ret0, _ := ret[0].(*cloudtrail.LookupEventsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupEvents indicates an expected call of LookupEvents.
func (mr *MockCloudTrailAPIMockRecorder) LookupEvents(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupEvents", reflect.TypeOf((*MockCloudTrailAPI)(nil).LookupEvents), varargs...)
}

// MockStsAPI is a mock of StsAPI interface.
type MockStsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockStsAPIMockRecorder
	isgomock struct{}
}

// MockStsAPIMockRecorder is the mock recorder for MockStsAPI.
type MockStsAPIMockRecorder struct {
	mock *MockStsAPI
}

// NewMockStsAPI creates a new mock instance.
func NewMockStsAPI(ctrl *gomock.Controller) *MockStsAPI {
	mock := &MockStsAPI{ctrl: ctrl}
	mock.recorder = &MockStsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStsAPI) EXPECT() *MockStsAPIMockRecorder {
	return m.recorder
}

// AssumeRole mocks base method.
func (m *MockStsAPI) AssumeRole(ctx context.Context, in *sts.AssumeRoleInput, optFns ...func(*sts.Options)) (*sts.AssumeRoleOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AssumeRole", varargs...)
	ret0, _ := ret[0].(*sts.AssumeRoleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssumeRole indicates an expected call of AssumeRole.
func (mr *MockStsAPIMockRecorder) AssumeRole(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssumeRole", reflect.TypeOf((*MockStsAPI)(nil).AssumeRole), varargs...)
}

// MockAgentCoreAPI is a mock of AgentCoreAPI interface.
type MockAgentCoreAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCoreAPIMockRecorder
	isgomock struct{}
}

// MockAgentCoreAPIMockRecorder is the mock recorder for MockAgentCoreAPI.
type MockAgentCoreAPIMockRecorder struct {
	mock *MockAgentCoreAPI
}

// NewMockAgentCoreAPI creates a new mock instance.
func NewMockAgentCoreAPI(ctrl *gomock.Controller) *MockAgentCoreAPI {
	mock := &MockAgentCoreAPI{ctrl: ctrl}
	mock.recorder = &MockAgentCoreAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCoreAPI) EXPECT() *MockAgentCoreAPIMockRecorder {
	return m.recorder
}

// InvokeAgentRuntime mocks base method.
func (m *MockAgentCoreAPI) InvokeAgentRuntime(ctx context.Context, in *bedrockagentcore.InvokeAgentRuntimeInput, optFns ...func(*bedrockagentcore.Options)) (*bedrockagentcore.InvokeAgentRuntimeOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InvokeAgentRuntime", varargs...)
	ret0, _ := ret[0].(*bedrockagentcore.InvokeAgentRuntimeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InvokeAgentRuntime indicates an expected call of InvokeAgentRuntime.
func (mr *MockAgentCoreAPIMockRecorder) InvokeAgentRuntime(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokeAgentRuntime", reflect.TypeOf((*MockAgentCoreAPI)(nil).InvokeAgentRuntime), varargs...)
}

// MockRoute53API is a mock of Route53API interface.
type MockRoute53API struct {
	ctrl     *gomock.Controller
	recorder *MockRoute53APIMockRecorder
	isgomock struct{}
}

// MockRoute53APIMockRecorder is the mock recorder for MockRoute53API.
type MockRoute53APIMockRecorder struct {
	mock *MockRoute53API
}

// NewMockRoute53API creates a new mock instance.
func NewMockRoute53API(ctrl *gomock.Controller) *MockRoute53API {
	mock := &MockRoute53API{ctrl: ctrl}
	mock.recorder = &MockRoute53APIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoute53API) EXPECT() *MockRoute53APIMockRecorder {
	return m.recorder
}

// ListHostedZonesByName mocks base method.
func (m *MockRoute53API) ListHostedZonesByName(ctx context.Context, in *route53.ListHostedZonesByNameInput, optFns ...func(*route53.Options)) (*route53.ListHostedZonesByNameOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListHostedZonesByName", varargs...)
	ret0, _ := ret[0].(*route53.ListHostedZonesByNameOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHostedZonesByName indicates an expected call of ListHostedZonesByName.
func (mr *MockRoute53APIMockRecorder) ListHostedZonesByName(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHostedZonesByName", reflect.TypeOf((*MockRoute53API)(nil).ListHostedZonesByName), varargs...)
}

// ListResourceRecordSets mocks base method.
func (m *MockRoute53API) ListResourceRecordSets(ctx context.Context, in *route53.ListResourceRecordSetsInput, optFns ...func(*route53.Options)) (*route53.ListResourceRecordSetsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListResourceRecordSets", varargs...)
	ret0, _ := ret[0].(*route53.ListResourceRecordSetsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResourceRecordSets indicates an expected call of ListResourceRecordSets.
func (mr *MockRoute53APIMockRecorder) ListResourceRecordSets(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourceRecordSets", reflect.TypeOf((*MockRoute53API)(nil).ListResourceRecordSets), varargs...)
}

// MockELBV2API is a mock of ELBV2API interface.
type MockELBV2API struct {
	ctrl     *gomock.Controller
	recorder *MockELBV2APIMockRecorder
	isgomock struct{}
}

// MockELBV2APIMockRecorder is the mock recorder for MockELBV2API.
type MockELBV2APIMockRecorder struct {
	mock *MockELBV2API
}

// NewMockELBV2API creates a new mock instance.
func NewMockELBV2API(ctrl *gomock.Controller) *MockELBV2API {
	mock := &MockELBV2API{ctrl: ctrl}
	mock.recorder = &MockELBV2APIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockELBV2API) EXPECT() *MockELBV2APIMockRecorder {
	return m.recorder
}

// DescribeLoadBalancers mocks base method.
func (m *MockELBV2API) DescribeLoadBalancers(ctx context.Context, in *elasticloadbalancingv2.DescribeLoadBalancersInput, optFns ...func(*elasticloadbalancingv2.Options)) (*elasticloadbalancingv2.DescribeLoadBalancersOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeLoadBalancers", varargs...)
	ret0, _ := ret[0].(*elasticloadbalancingv2.DescribeLoadBalancersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeLoadBalancers indicates an expected call of DescribeLoadBalancers.
func (mr *MockELBV2APIMockRecorder) DescribeLoadBalancers(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeLoadBalancers", reflect.TypeOf((*MockELBV2API)(nil).DescribeLoadBalancers), varargs...)
}

// DescribeTargetGroups mocks base method.
func (m *MockELBV2API) DescribeTargetGroups(ctx context.Context, in *elasticloadbalancingv2.DescribeTargetGroupsInput, optFns ...func(*elasticloadbalancingv2.Options)) (*elasticloadbalancingv2.DescribeTargetGroupsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeTargetGroups", varargs...)
	ret0, _ := ret[0].(*elasticloadbalancingv2.DescribeTargetGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeTargetGroups indicates an expected call of DescribeTargetGroups.
func (mr *MockELBV2APIMockRecorder) DescribeTargetGroups(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeTargetGroups", reflect.TypeOf((*MockELBV2API)(nil).DescribeTargetGroups), varargs...)
}

// DescribeTargetHealth mocks base method.
func (m *MockELBV2API) DescribeTargetHealth(ctx context.Context, in *elasticloadbalancingv2.DescribeTargetHealthInput, optFns ...func(*elasticloadbalancingv2.Options)) (*elasticloadbalancingv2.DescribeTargetHealthOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeTargetHealth", varargs...)
	ret0, _ := ret[0].(*elasticloadbalancingv2.DescribeTargetHealthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeTargetHealth indicates an expected call of DescribeTargetHealth.
func (mr *MockELBV2APIMockRecorder) DescribeTargetHealth(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeTargetHealth", reflect.TypeOf((*MockELBV2API)(nil).DescribeTargetHealth), varargs...)
}

// MockELBAPI is a mock of ELBAPI interface.
type MockELBAPI struct {
	ctrl     *gomock.Controller
	recorder *MockELBAPIMockRecorder
	isgomock struct{}
}

// MockELBAPIMockRecorder is the mock recorder for MockELBAPI.
type MockELBAPIMockRecorder struct {
	mock *MockELBAPI
}

// NewMockELBAPI creates a new mock instance.
func NewMockELBAPI(ctrl *gomock.Controller) *MockELBAPI {
	mock := &MockELBAPI{ctrl: ctrl}
	mock.recorder = &MockELBAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockELBAPI) EXPECT() *MockELBAPIMockRecorder {
	return m.recorder
}

// DescribeInstanceHealth mocks base method.
func (m *MockELBAPI) DescribeInstanceHealth(ctx context.Context, in *elasticloadbalancing.DescribeInstanceHealthInput, optFns ...func(*elasticloadbalancing.Options)) (*elasticloadbalancing.DescribeInstanceHealthOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeInstanceHealth", varargs...)
	ret0, _ := ret[0].(*elasticloadbalancing.DescribeInstanceHealthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeInstanceHealth indicates an expected call of DescribeInstanceHealth.
func (mr *MockELBAPIMockRecorder) DescribeInstanceHealth(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeInstanceHealth", reflect.TypeOf((*MockELBAPI)(nil).DescribeInstanceHealth), varargs...)
}

// DescribeLoadBalancers mocks base method.
func (m *MockELBAPI) DescribeLoadBalancers(ctx context.Context, in *elasticloadbalancing.DescribeLoadBalancersInput, optFns ...func(*elasticloadbalancing.Options)) (*elasticloadbalancing.DescribeLoadBalancersOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeLoadBalancers", varargs...)
	ret0, _ := ret[0].(*elasticloadbalancing.DescribeLoadBalancersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeLoadBalancers indicates an expected call of DescribeLoadBalancers.
func (mr *MockELBAPIMockRecorder) DescribeLoadBalancers(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeLoadBalancers", reflect.TypeOf((*MockELBAPI)(nil).DescribeLoadBalancers), varargs...)
}

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FindCLBByDNSName mocks base method.
func (m *MockClient) FindCLBByDNSName(dnsName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCLBByDNSName", dnsName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCLBByDNSName indicates an expected call of FindCLBByDNSName.
func (mr *MockClientMockRecorder) FindCLBByDNSName(dnsName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCLBByDNSName", reflect.TypeOf((*MockClient)(nil).FindCLBByDNSName), dnsName)
}

// FindHostedZone mocks base method.
func (m *MockClient) FindHostedZone(dnsName string, private bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindHostedZone", dnsName, private)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindHostedZone indicates an expected call of FindHostedZone.
func (mr *MockClientMockRecorder) FindHostedZone(dnsName, private any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindHostedZone", reflect.TypeOf((*MockClient)(nil).FindHostedZone), dnsName, private)
}

// FindNLBByDNSName mocks base method.
func (m *MockClient) FindNLBByDNSName(dnsName string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNLBByDNSName", dnsName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindNLBByDNSName indicates an expected call of FindNLBByDNSName.
func (mr *MockClientMockRecorder) FindNLBByDNSName(dnsName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNLBByDNSName", reflect.TypeOf((*MockClient)(nil).FindNLBByDNSName), dnsName)
}

// GetBaseConfig mocks base method.
func (m *MockClient) GetBaseConfig() *aws.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseConfig")
	ret0, _ := ret[0].(*aws.Config)
	return ret0
}

// GetBaseConfig indicates an expected call of GetBaseConfig.
func (mr *MockClientMockRecorder) GetBaseConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseConfig", reflect.TypeOf((*MockClient)(nil).GetBaseConfig))
}

// GetCLBInstanceHealth mocks base method.
func (m *MockClient) GetCLBInstanceHealth(lbName string) ([]aws0.CLBInstanceHealth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCLBInstanceHealth", lbName)
	ret0, _ := ret[0].([]aws0.CLBInstanceHealth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCLBInstanceHealth indicates an expected call of GetCLBInstanceHealth.
func (mr *MockClientMockRecorder) GetCLBInstanceHealth(lbName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCLBInstanceHealth", reflect.TypeOf((*MockClient)(nil).GetCLBInstanceHealth), lbName)
}

// GetNLBTargetHealth mocks base method.
func (m *MockClient) GetNLBTargetHealth(lbARN string) ([]aws0.NLBTargetHealth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNLBTargetHealth", lbARN)
	ret0, _ := ret[0].([]aws0.NLBTargetHealth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNLBTargetHealth indicates an expected call of GetNLBTargetHealth.
func (mr *MockClientMockRecorder) GetNLBTargetHealth(lbARN any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNLBTargetHealth", reflect.TypeOf((*MockClient)(nil).GetNLBTargetHealth), lbARN)
}

// GetRouteTableForSubnet mocks base method.
func (m *MockClient) GetRouteTableForSubnet(subnetID string) (types0.RouteTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouteTableForSubnet", subnetID)
	ret0, _ := ret[0].(types0.RouteTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRouteTableForSubnet indicates an expected call of GetRouteTableForSubnet.
func (mr *MockClientMockRecorder) GetRouteTableForSubnet(subnetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouteTableForSubnet", reflect.TypeOf((*MockClient)(nil).GetRouteTableForSubnet), subnetID)
}

// GetSecurityGroupID mocks base method.
func (m *MockClient) GetSecurityGroupID(infraID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityGroupID", infraID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityGroupID indicates an expected call of GetSecurityGroupID.
func (mr *MockClientMockRecorder) GetSecurityGroupID(infraID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityGroupID", reflect.TypeOf((*MockClient)(nil).GetSecurityGroupID), infraID)
}

// GetSubnetID mocks base method.
func (m *MockClient) GetSubnetID(infraID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetID", infraID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetID indicates an expected call of GetSubnetID.
func (mr *MockClientMockRecorder) GetSubnetID(infraID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetID", reflect.TypeOf((*MockClient)(nil).GetSubnetID), infraID)
}

// GetVpcDhcpConfiguration mocks base method.
func (m *MockClient) GetVpcDhcpConfiguration(infraID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVpcDhcpConfiguration", infraID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVpcDhcpConfiguration indicates an expected call of GetVpcDhcpConfiguration.
func (mr *MockClientMockRecorder) GetVpcDhcpConfiguration(infraID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVpcDhcpConfiguration", reflect.TypeOf((*MockClient)(nil).GetVpcDhcpConfiguration), infraID)
}

// HasResourceRecordSet mocks base method.
func (m *MockClient) HasResourceRecordSet(hostedZoneID, recordName, recordType string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasResourceRecordSet", hostedZoneID, recordName, recordType)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasResourceRecordSet indicates an expected call of HasResourceRecordSet.
func (mr *MockClientMockRecorder) HasResourceRecordSet(hostedZoneID, recordName, recordType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasResourceRecordSet", reflect.TypeOf((*MockClient)(nil).HasResourceRecordSet), hostedZoneID, recordName, recordType)
}

// IsSubnetPrivate mocks base method.
func (m *MockClient) IsSubnetPrivate(subnet string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSubnetPrivate", subnet)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSubnetPrivate indicates an expected call of IsSubnetPrivate.
func (mr *MockClientMockRecorder) IsSubnetPrivate(subnet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSubnetPrivate", reflect.TypeOf((*MockClient)(nil).IsSubnetPrivate), subnet)
}

// ListNonRunningInstances mocks base method.
func (m *MockClient) ListNonRunningInstances(infraID string) ([]types0.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNonRunningInstances", infraID)
	ret0, _ := ret[0].([]types0.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNonRunningInstances indicates an expected call of ListNonRunningInstances.
func (mr *MockClientMockRecorder) ListNonRunningInstances(infraID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNonRunningInstances", reflect.TypeOf((*MockClient)(nil).ListNonRunningInstances), infraID)
}

// ListRunningInstances mocks base method.
func (m *MockClient) ListRunningInstances(infraID string) ([]types0.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRunningInstances", infraID)
	ret0, _ := ret[0].([]types0.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRunningInstances indicates an expected call of ListRunningInstances.
func (mr *MockClientMockRecorder) ListRunningInstances(infraID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRunningInstances", reflect.TypeOf((*MockClient)(nil).ListRunningInstances), infraID)
}

// PollInstanceStopEventsFor mocks base method.
func (m *MockClient) PollInstanceStopEventsFor(instances []types0.Instance, retryTimes int) ([]types.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollInstanceStopEventsFor", instances, retryTimes)
	ret0, _ := ret[0].([]types.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PollInstanceStopEventsFor indicates an expected call of PollInstanceStopEventsFor.
func (mr *MockClientMockRecorder) PollInstanceStopEventsFor(instances, retryTimes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollInstanceStopEventsFor", reflect.TypeOf((*MockClient)(nil).PollInstanceStopEventsFor), instances, retryTimes)
}
