apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: configuration-anomaly-detection-template
parameters:
- name: IMAGE_TAG
  value: v0.0.0
- name: REGISTRY_IMG
  value: quay.io/app-sre/configuration-anomaly-detection
- name: NAMESPACE_NAME
  value: configuration-anomaly-detection
objects:
- apiVersion: triggers.tekton.dev/v1beta1
  kind: TriggerBinding
  metadata:
    name: cad-check-trigger
  spec:
    params:
    - name: payload
      value: $(body)
- apiVersion: triggers.tekton.dev/v1alpha1
  kind: TriggerTemplate
  metadata:
    annotations:
      triggers.tekton.dev/old-escape-quotes: "true"
    name: cad-check-trigger-template
  spec:
    params:
    - description: The event that triggered the webhook.
      name: payload
    resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: cad-check-$(uid)
      spec:
        params:
        - name: payload
          value: $(tt.params.payload)
        pipelineRef:
          name: cad-checks-pipeline
        serviceAccountName: cad-sa
        timeout: 30m
- apiVersion: triggers.tekton.dev/v1beta1
  kind: Trigger
  metadata:
    name: cad-pipe-listener
  spec:
    bindings:
    - ref: cad-check-trigger
    interceptors:
    - params:
      - name: filter
        value: header.canonical('X-Secret-Token').compareSecret('X_SECRET_TOKEN',
          'cad-pd-token')
      ref:
        name: cel
    template:
      ref: cad-check-trigger-template
- apiVersion: triggers.tekton.dev/v1alpha1
  kind: EventListener
  metadata:
    annotations:
      triggers.tekton.dev/old-escape-quotes: "true"
    name: cad-event-listener
  spec:
    triggers:
    - triggerRef: cad-pipe-listener
- apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    name: cad-checks-pipeline
  spec:
    params:
    - description: Json string of the event data
      name: payload
      type: string
    tasks:
    - name: perform-cad-checks
      params:
      - name: payload
        value: $(params.payload)
      - name: pipeline-name
        value: $(context.pipelineRun.name)
      taskRef:
        name: cad-checks
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pipelinerun-counts
  spec:
    hard:
      count/pipelineruns.tekton.dev: "1000"
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cad-sa
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: cad-pipelinerun-role
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - secrets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - tekton.dev
    resources:
    - pipelineruns
    verbs:
    - create
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: cad-pipelinerun-rolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: cad-pipelinerun-role
  subjects:
  - kind: ServiceAccount
    name: cad-sa
- apiVersion: v1
  kind: Secret
  metadata:
    name: cad-aws-credentials
  stringData:
    AWS_ACCESS_KEY_ID: CHANGEME
    AWS_DEFAULT_REGION: CHANGEME
    AWS_SECRET_ACCESS_KEY: CHANGEME
    AWS_SESSION_TOKEN: CHANGEME
    CAD_AWS_CSS_JUMPROLE: CHANGEME
    CAD_AWS_SUPPORT_JUMPROLE: CHANGEME
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    name: cad-ocm-client-secret
  stringData:
    CAD_OCM_CLIENT_ID: CHANGEME
    CAD_OCM_CLIENT_SECRET: CHANGEME
    CAD_OCM_URL: https://api.stage.openshift.com
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    name: cad-pd-token
  stringData:
    CAD_ESCALATION_POLICY: CHANGEME
    CAD_PD_EMAIL: CHANGEME
    CAD_PD_PW: CHANGEME
    CAD_PD_TOKEN: CHANGEME
    CAD_PD_USERNAME: CHANGEME
    CAD_SILENT_POLICY: CHANGEME
    PD_SIGNATURE: CHANGEME
    X_SECRET_TOKEN: CHANGEME
  type: Opaque
- apiVersion: tekton.dev/v1beta1
  kind: Task
  metadata:
    name: cad-checks
  spec:
    params:
    - description: Json string of the event data
      name: payload
      type: string
    - description: The pipelinerun name
      name: pipeline-name
      type: string
    steps:
    - args:
      - |-
        # save the payload to a file
        folder=$(mktemp -d)
        file=${folder}/payload.json
        cat << EOF > $file
        $(params.payload)
        EOF
        # run the cadctl command
        PIPELINE_NAME=$(params.pipeline-name) cadctl investigate --payload-path $file
      command:
      - /bin/bash
      - -c
      env:
      - name: CAD_PROMETHEUS_GATEWAY
        value: aggregation-pushgateway:9091
      envFrom:
      - secretRef:
          name: cad-aws-credentials
      - secretRef:
          name: cad-ocm-client-secret
      - secretRef:
          name: cad-pd-token
      image: ${REGISTRY_IMG}:${IMAGE_TAG}
      name: check-infrastructure
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    labels:
      tektonconfig.operator.tekton.dev/pruner: "true"
    name: tekton-resource-pruner
  spec:
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 1
    jobTemplate:
      spec:
        backoffLimit: 3
        template:
          spec:
            containers:
            - args:
              - tkn pipelinerun delete --keep=100 -f
              command:
              - /bin/sh
              - -c
              image: quay.io/openshift-pipeline/openshift-pipelines-pipelines-cli-tkn-rhel8@sha256:e1fa47811f156e48a61741aabe73ef85078960567822a4b23c174c0d9b4d0ee6
              imagePullPolicy: IfNotPresent
              name: tekton-resource-pruner
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: FallbackToLogsOnError
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            schedulerName: default-scheduler
            serviceAccount: cad-tekton-pruner
            serviceAccountName: cad-tekton-pruner
            terminationGracePeriodSeconds: 30
        ttlSecondsAfterFinished: 3600
    schedule: 0 * * * *
    successfulJobsHistoryLimit: 3
    suspend: false
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cad-tekton-pruner
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: cad-tekton-pruner-role
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - delete
    - get
    - watch
    - list
  - apiGroups:
    - tekton.dev
    resources:
    - pipelineruns
    - taskruns
    verbs:
    - delete
    - list
    - get
    - watch
  - apiGroups:
    - batch
    resources:
    - jobs
    verbs:
    - create
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: cad-tekton-pruner-role-binding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: cad-tekton-pruner-role
  subjects:
  - kind: ServiceAccount
    name: cad-tekton-pruner
