name: Auto tidy interceptor after cadctl changes

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**/*.go'
      - '!interceptor/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run go mod tidy in interceptor
        working-directory: interceptor
        run: go mod tidy

      - name: Check for changes when run go mod tidy in interceptor
        id: diffcheck
        run: |
          if [[ -n "$(git status --porcelain interceptor/go.mod interceptor/go.sum)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if there are changes
        if: steps.diffcheck.outputs.changes == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          message: "On PR: tidy interceptor go.mod after cadctl go.mod update"
          add: "interceptor/go.mod interceptor/go.sum"
